services:
  - type: web
    name: rishi-gupta-portfolio
    runtime: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.4"
